query allRooms {
  allRooms {
    id
    title
    description
    number
    type
    sleeps
    cost
  }
}

# adjust checkin and checkout dates to find available rooms
query availableRooms {
  availableRooms(checkIn: "2024-02-16", checkOut: "2024-02-17") {
    id
    title
    description
    number
    type
    sleeps
    cost
  }
}
