
  mutation createBooking($data: BookingCreateInput!) {
  createBooking(data: $data) {
    id
    createdAt
    updatedAt
    checkIn
    checkOut
    paid
    room {
      id
      title
      description
      number
      type
      sleeps
      cost
    }
    customer {
      id
      name
      email
      phone
    }
  }
}


{
  "data": {
    "checkIn": "2024-02-14T12:00:00Z",
    "checkOut": "2024-02-16T12:00:00Z",
    "paid": true,
    "roomId": 1,
    "customerId": 2
  }
}



# toggle paid for an exisitng booking. update id and isPaid param to match booking
mutation {
  togglePaidBooking(id:1, isPaid:true) {
    id
    createdAt
    updatedAt
    checkIn
    checkOut
    paid
    room {
    	id
      title
      description
      number
      type
      sleeps
      cost
    }
    customer {
      id
      name
      email
      phone
    }
  }
}