query {
  allBookings {
    id
    paid
    room {
      id
      title
      description
      number
      type
      sleeps
      cost
    }
    customer {
      name
      email
      phone
    }
  }
}
