query {
  allCustomers {
    id
    name
    email
    phone
  }
  allRooms {
    id
    title
    description
    number
    type
    sleeps
    cost
  }

  allBookings {
    id
    paid
    room {
      id
      title
      description
      number
      type
      sleeps
      cost
    }
    customer {
      name
      email
      phone
    }
  }
}

mutation {
  createCustomer(
    data: {
      email: "customer@example.com"
      name: "John Doe"
      phone: "123-456-7890"
    }
  ) {
    id
    createdAt
    updatedAt
    email
    name
    phone
  }

  createRoom(
    data: {
      title: "Room 1"
      description: "A nice room with a view"
      number: 1
      type: "SINGLE"
      sleeps: 1
      cost: 100
    }
  ) {
    id
    createdAt
    updatedAt
    title
    description
    number
    type
    sleeps
    cost
  }
}
