query AllRooms {
  allRooms {
    id
    title
    description
    number
    type
    sleeps
    cost
  }
}

# adjust checkin and checkout dates to find available rooms
query FindAvailableRooms {
  availableRooms(
    checkIn: "2024-02-16T01:00:00Z"
    checkOut: "2024-02-17T12:00:00Z"
  ) {
    id
    title
    description
    number
    type
    sleeps
    cost
  }
}
